{{- if .Values.loginapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "k8s-ldap.name" . }}
    chart: {{ template "k8s-ldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.loginapp.name }}
  name: {{ template "k8s-ldap.loginapp.fullname" . }}
spec:
  replicas: {{ .Values.loginapp.replicas }}
  selector:
    matchLabels:
      app: {{ template "k8s-ldap.name" . }}
      component: {{ .Values.loginapp.name }}
  template:
    metadata:
    {{- if .Values.loginapp.podAnnotations }}
      annotations:
{{ toYaml .Values.loginapp.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "k8s-ldap.name" . }}
        component: {{ .Values.loginapp.name }}
    spec:
      containers:
      - image: {{ .Values.loginapp.image.repository }}:{{ .Values.loginapp.image.tag }}
        imagePullPolicy: {{ .Values.loginapp.image.pullPolicy }}
        name: {{ template "k8s-ldap.name" . }}-{{ .Values.loginapp.name }}
        command: ["/loginapp", "/app/config.yaml"]
        ports:
        - name: http
          containerPort: {{ .Values.loginapp.port }}
        volumeMounts:
        - name: config
          mountPath: /app/
        - name: ca
          mountPath: /etc/ssl/
      {{- if .Values.loginapp.resources }}
        resources:
{{ toYaml .Values.loginapp.resources | indent 8 }}
      {{- end }}
        #readinessProbe:
        #  httpGet:
        #    path: /loginapp/healthz
        #    port: {{ .Values.loginapp.port }}
        #  timeoutSeconds: 5
        #  periodSeconds: 5
        #  failureThreshold: 5
        #livenessProbe:
        #  httpGet:
        #    path: /loginapp/healthz
        #    port: {{ .Values.loginapp.port }}
        #  initialDelaySeconds: 30
        #  periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: {{ template "k8s-ldap.loginapp.fullname" . }}
          items:
          - key: config.yaml
            path: config.yaml
      - name: ca
        configMap:
          name: {{ .Release.Name }}-ca
          items:
          - key: ca.pem
            path: ca.pem
    {{- if .Values.loginapp.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.loginapp.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.loginapp.tolerations }}
      tolerations:
{{ toYaml .Values.loginapp.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.loginapp.affinity }}
      affinity:
{{ toYaml .Values.loginapp.affinity | indent 8 }}
    {{- end -}}
{{- end -}}
